version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: standard
    stream: ext://sys.stdout
  info_file:
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    formatter: standard
    filename: logs/info.log
    when: midnight
    interval: 1
    backupCount: 7  # keep a week of logs
    utc: true

loggers:
  gridgpt:
    level: INFO
    handlers: [console, info_file]
    propagate: false

root:
  level: INFO
  handlers: [console, info_file]
